version: '3'

services:
  postgres:
    image: 'postgres:latest'
    restart: 'always'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=nfl-rushing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - './db/data:/var/lib/postgresql/data/'
      - './db/init:/docker-entrypoint-initdb.d'